### ISSUE TITLE
Apache Avro depends on Jackson 1.9(!)

### ISSUE THREAD

**Issue by dsyer** [viniciusccarvalho/schema-evolution-samples#3]
It would be good to understand why, and remove it if possible? Or maybe we are just using an old version here?

**Comment by viniciusccarvalho** [comment]
I don't think we can remove it, since schemas are defined in JSON and the Parser imports  `org.codehaus.jackson.JsonFactory` and not `com.fasterxml.jackson.core.JacksonFactory`. Avro 1.8.0 is already the latest

Related: https://issues.apache.org/jira/browse/AVRO-1126
